import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

def send_email_with_attachments(recipients, filenames):
    print("Sending email...")
    msg = MIMEMultipart()
    msg['From'] = "awh_project_demo@outlook.com"
    msg['To'] = ", ".join(recipients)
    msg['Subject'] = "CSV Files from Raspberry Pi"
    msg.attach(MIMEText("Attached are the CSV files generated by Raspberry Pi.", 'plain'))

    for filename in filenames:
        with open(filename, "rb") as attachment:
            part = MIMEBase('application', 'octet-stream')
            part.set_payload(attachment.read())
            encoders.encode_base64(part)
            part.add_header('Content-Disposition', f'attachment; filename= {filename}')
            msg.attach(part)

    try:
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login("awhproject2024@gmail.com", "yrxzscumxhjecqeo")
        server.sendmail("awhproject2024@gmail.com", recipients, msg.as_string())
        server.quit()
        print("Email sent successfully")
    except Exception as e:
        print(f"Failed to send email: {e}")

# Test the function
recipients = ["nakaruk@gmail.com", "a.nakaruk@gmail.com"]  # Replace with actual valid email addresses
filenames = ["test_file1.csv", "test_file2.csv"]  # Replace with actual file paths
send_email_with_attachments(recipients, filenames)
